services:
  api:
    build:
      context: .
      target: builder
    container_name: fastapi-application
    environment:
      PORT: 8000
    ports:
      - '8000:8000'
    restart: "no"

  mysql:
    image: mysql:latest
    container_name: fastapi-db
    environment:
      MYSQL_ROOT_PASSWORD: fastapiroot
      MYSQL_DATABASE: fastapi
      MYSQL_USER: fastapi
      MYSQL_PASSWORD: "QWERTYY12345!"
    ports:
      - '3306:3306'
    volumes:
        - db_data:/var/lib/mysql

  phpmyadmin:
       image: phpmyadmin/phpmyadmin
       container_name: phpmyadmin
       environment:
         PMA_HOST: mysql
         PMA_USER: fastapi
         PMA_PASSWORD: "QWERTYY12345!"
       ports:
         - '8081:80'      


volumes:
  db_data: